services:
  ros2:
    image: ub-cavas/ros2-lincoln
    container_name: ros2_c
    stdin_open: true
    tty: true
    runtime: nvidia
    gpus: all
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY:-}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/home/${USERNAME}/.Xauthority
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp:/tmp
      - $HOST_DATA_PATH:/host_data
    devices:
      - /dev:/dev
      - /run/udev:/run/udev:ro



# image: ${ROS2_WS_CONTAINER_NAME}-${USE_ROS_DISTRO}
# stdin_open: true
# tty: true
# ipc: host
# pid: host
# user: ${USERNAME}
# environment:
#   - QT_X11_NO_MITSHM=1
#   - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
# volumes:
#   - $ROS2_WS_MOUNT:/home/${USERNAME}/$ROS2_WS_CONTAINER_NAME