services:
  autoware:
    image: ubcavas/autoware-lincoln
    container_name: autoware_c
    stdin_open: true
    tty: true
    runtime: nvidia
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY:-}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - $HOST_DATA_PATH:/host_data
    devices:
      - /dev:/dev
      - /run/udev:/run/udev:ro
